### ISSUE TITLE
Entregas

### ISSUE THREAD

**Issue by astenuz** [datasketch/MOVID19#10]
Hola! Entregamos a tiempo pero vemos que solo hay dos pull request. Piensan extender la fecha de entrega? nos gustaria saber de ser asi, como funcionaria la evaluacion.

**Comment by jpmarindiaz** [comment]
Ver actualización del README "Plazo extendido"

**Comment by astenuz** [comment]
Gracias! Podemos usar este tiempo para realizar ajustes a los informes? o sugieres mejor que dejemos lo que ya esta?

**Comment by jpmarindiaz** [comment]
Si, ajusten lo que quieran

**Comment by astenuz** [comment]
Perfecto, gracias

**Comment by juanvepi24** [comment]
Hola quisiera saber si mi archivo PDF fue recibido?
