### ISSUE TITLE
Dudas sobre la estructura del entregable.

### ISSUE THREAD

**Issue by astenuz** [datasketch/MOVID19#6]
Hola! nos gustaria resolver algunas dudas respecto a la carpeta de entregables:

1. La carpeta analisis, deberia tener todo el codigo y los notebooks de analisis verdad? Aca es necesario llenar el md con todos los detalles?, o puede hacerse referecncia a los diferentes notebooks?
2. Cual es el proposito de la carpeta visualizaciones? no se colocarian las visualizaciones de resultado en resultados?

Gracias, quedamos atentos

**Comment by jpmarindiaz** [comment]
1. En lo posible dejar el código disponible ahí mismo en la carpeta de análisis, uno de los criterios de evaluación es la apertura y eso contaría en ese componente.
El .md de análisis debe describir los análisis que se hicieron y los pasos para replicarlos.

2. La carpeta de visualizaciones es opcional, sin embargo recomendada. Ya que no todo lo que se hace en visualización necesariamente soporta los resultados, por ejemplo, visualizaciones de EDA (exploratory data analysis - análisis exploratorio de datos) normalmente no son un hallazgo pues pueden no llevar a nada, sin embargo hacen parte del proceso de documentación del análisis.

**Comment by astenuz** [comment]
Gracias, claro para el primer punto. Para el segundo, supongo que esta bien si estas visualizaciones estan tambien en los notebooks de analisis verdad?

**Comment by jpmarindiaz** [comment]
si

**Comment by astenuz** [comment]
Perfecto, otra duda respecto a estas carpetas, la carpeta `data` debe contener los archivos usados? Tenemos el problema que los archivos de movilidad son muy pesados y no parece buena idea subirlos.

**Comment by jpmarindiaz** [comment]
Esto ya se explica que directamente en la plantilla. Si los archivos son pesados se pueden vincular a cualquier url pública.
